# Generated by Django 3.2.9 on 2022-01-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('habitat', models.CharField(max_length=100)),
            ],
        ),
    ]
